import { Difficulty, Word } from './types';

const WORDS_PER_DIFFICULTY = 150;

type Seed = {
  text: string;
  category: string;
};

const toSeeds = (category: string, words: string[]): Seed[] => {
  return words.map((text) => ({ text, category }));
};

const buildWords = (prefix: string, difficulty: Difficulty, seeds: Seed[]): Word[] => {
  return seeds.map((seed, index) => ({
    id: `${prefix}${index + 1}`,
    text: seed.text,
    category: seed.category,
    difficulty,
  }));
};

const assertCount = (label: string, count: number) => {
  if (count !== WORDS_PER_DIFFICULTY) {
    throw new Error(`Expected ${WORDS_PER_DIFFICULTY} words for ${label}, got ${count}`);
  }
};

export const CATEGORIES = ['Comida', 'Objetos', 'Animales', 'Profesiones', 'Lugares', 'Deportes', 'Tecnologia', 'Cultura', 'Naturaleza'];

const EASY_SEEDS: Seed[] = [
  ...toSeeds('Comida', [
    'Pizza',
    'Hamburguesa',
    'Pan',
    'Leche',
    'Manzana',
    'Huevo',
    'Queso',
    'Arroz',
    'Agua',
    'Chocolate',
    'Sopa',
    'Ensalada',
    'Galleta',
    'Yogur',
    'Platano',
    'Naranja',
    'Pasta',
  ]),
  ...toSeeds('Objetos', [
    'Mesa',
    'Silla',
    'Libro',
    'Lapiz',
    'Cama',
    'Coche',
    'Telefono',
    'Reloj',
    'Llave',
    'Zapato',
    'Vaso',
    'Papel',
    'Mochila',
    'Puerta',
    'Ventana',
    'Cuchara',
    'Toalla',
  ]),
  ...toSeeds('Animales', [
    'Perro',
    'Gato',
    'Leon',
    'Elefante',
    'Pajaro',
    'Pez',
    'Vaca',
    'Mono',
    'Caballo',
    'Tigre',
    'Conejo',
    'Oveja',
    'Pollo',
    'Pato',
    'Raton',
    'Arana',
    'Lobo',
  ]),
  ...toSeeds('Profesiones', [
    'Medico',
    'Profesor',
    'Bombero',
    'Policia',
    'Cocinero',
    'Pintor',
    'Piloto',
    'Panadero',
    'Cartero',
    'Jardinero',
    'Taxista',
    'Cantante',
    'Actor',
    'Dentista',
    'Enfermero',
    'Albanil',
    'Pescador',
  ]),
  ...toSeeds('Lugares', [
    'Playa',
    'Escuela',
    'Parque',
    'Hospital',
    'Cine',
    'Supermercado',
    'Restaurante',
    'Casa',
    'Oficina',
    'Granja',
    'Zoologico',
    'Montana',
    'Puerto',
    'Estacion',
    'Aeropuerto',
    'Biblioteca',
    'Museo',
  ]),
  ...toSeeds('Deportes', [
    'Futbol',
    'Tenis',
    'Natacion',
    'Baloncesto',
    'Ciclismo',
    'Rugby',
    'Golf',
    'Boxeo',
    'Voleibol',
    'Carrera',
    'Patinaje',
    'Billar',
    'Karate',
    'Surf',
    'Beisbol',
    'Atletismo',
    'Ajedrez',
  ]),
  ...toSeeds('Tecnologia', [
    'Televisor',
    'Internet',
    'Ordenador',
    'Movil',
    'Camara',
    'Radio',
    'Altavoz',
    'Auriculares',
    'Tablet',
    'Impresora',
    'Teclado',
    'Raton',
    'Cargador',
    'Microfono',
    'Consola',
    'Pantalla',
  ]),
  ...toSeeds('Cultura', [
    'Musica',
    'Baile',
    'Pelicula',
    'Teatro',
    'Novela',
    'Poema',
    'Cuento',
    'Comic',
    'Fotografia',
    'Concierto',
    'Escultura',
    'Cancion',
    'Fiesta',
    'Dibujo',
    'Danza',
    'Pintura',
  ]),
  ...toSeeds('Naturaleza', [
    'Arbol',
    'Sol',
    'Lluvia',
    'Flor',
    'Rio',
    'Mar',
    'Nube',
    'Nieve',
    'Viento',
    'Luna',
    'Hielo',
    'Piedra',
    'Bosque',
    'Desierto',
    'Isla',
    'Volcan',
  ]),
];

const MEDIUM_SEEDS: Seed[] = [
  ...toSeeds('Comida', [
    'Sushi',
    'Paella',
    'Aguacate',
    'Garbanzo',
    'Croqueta',
    'Tortilla',
    'Lenteja',
    'Quinoa',
    'Almendra',
    'Canela',
    'Tofu',
    'Empanada',
    'Risotto',
    'Cuscus',
    'Wasabi',
    'Panini',
    'Kimchi',
  ]),
  ...toSeeds('Objetos', [
    'Grapadora',
    'Brujula',
    'Linterna',
    'Paraguas',
    'Diccionario',
    'Termometro',
    'Candado',
    'Martillo',
    'Destornillador',
    'Tripode',
    'Prismaticos',
    'Maletin',
    'Agenda',
    'Botiquin',
    'Tijeras',
    'Regla',
    'Serrucho',
  ]),
  ...toSeeds('Animales', [
    'Delfin',
    'Pinguino',
    'Jirafa',
    'Cocodrilo',
    'Aguila',
    'Canguro',
    'Pulpo',
    'Koala',
    'Guepardo',
    'Tortuga',
    'Iguana',
    'Flamenco',
    'Bisonte',
    'Nutria',
    'Foca',
    'Camaleon',
    'Cebra',
  ]),
  ...toSeeds('Profesiones', [
    'Astronauta',
    'Arquitecto',
    'Abogado',
    'Cientifico',
    'Periodista',
    'Veterinario',
    'Carpintero',
    'Disenador',
    'Fotografo',
    'Electricista',
    'Programador',
    'Chef',
    'Traductor',
    'Farmaceutico',
    'Psicologo',
    'Ingeniero',
    'Guia',
  ]),
  ...toSeeds('Lugares', [
    'Castillo',
    'Estadio',
    'Gimnasio',
    'Universidad',
    'Planetario',
    'Acuario',
    'Mirador',
    'Faro',
    'Monasterio',
    'Mercado',
    'Embalse',
    'Observatorio',
    'Bulevar',
    'Anfiteatro',
    'Auditorio',
    'Terminal',
    'Reserva',
  ]),
  ...toSeeds('Deportes', [
    'Esgrima',
    'Curling',
    'Pentatlon',
    'Triatlon',
    'Escalada',
    'Remo',
    'Halterofilia',
    'Gimnasia',
    'Taekwondo',
    'Piraguismo',
    'Badminton',
    'Hockey',
    'Waterpolo',
    'Esqui',
    'Snorkel',
    'Parkour',
    'Patin',
  ]),
  ...toSeeds('Tecnologia', [
    'Satelite',
    'Software',
    'Microscopio',
    'Telescopio',
    'Bateria',
    'Robot',
    'Dron',
    'Servidor',
    'Router',
    'Sensor',
    'Laser',
    'Memoria',
    'Procesador',
    'Algoritmo',
    'Circuito',
    'Proyector',
  ]),
  ...toSeeds('Cultura', [
    'Opera',
    'Mitologia',
    'Folclore',
    'Ceramica',
    'Arquitectura',
    'Biografia',
    'Historia',
    'Litografia',
    'Orquesta',
    'Tapiz',
    'Mural',
    'Caligrafia',
    'Cronica',
    'Retablo',
    'Narrativa',
    'Grabado',
  ]),
  ...toSeeds('Naturaleza', [
    'Cascada',
    'Selva',
    'Oceano',
    'Cueva',
    'Terremoto',
    'Relampago',
    'Acantilado',
    'Arrecife',
    'Tornado',
    'Aurora',
    'Manglar',
    'Pradera',
    'Laguna',
    'Sabana',
    'Cordillera',
    'Estuario',
  ]),
];

const HARD_SEEDS: Seed[] = [
  ...toSeeds('Comida', [
    'Azafran',
    'Trufa',
    'Miso',
    'Kombucha',
    'Tempeh',
    'Edamame',
    'Ghee',
    'Semola',
    'Tapioca',
    'Cardamomo',
    'AnisEstrellado',
    'Kefir',
    'Bulgur',
    'Harissa',
    'Tamarindo',
    'Matcha',
    'Shiitake',
  ]),
  ...toSeeds('Objetos', [
    'Sextante',
    'Metronomo',
    'Barometro',
    'Relicario',
    'Cronometro',
    'Anemometro',
    'Calibrador',
    'Osciloscopio',
    'Periscopio',
    'Astrolabio',
    'Sismografo',
    'Pluviometro',
    'Micrometro',
    'Dinamometro',
    'Polarimetro',
    'Termostato',
    'Voltimetro',
  ]),
  ...toSeeds('Animales', [
    'Ornitorrinco',
    'Quokka',
    'Caracal',
    'Narval',
    'Okapi',
    'Lince',
    'Ibice',
    'Suricata',
    'Tarsero',
    'Ajolote',
    'Tucan',
    'Pangolin',
    'Armadillo',
    'Caiman',
    'Manati',
    'Comadreja',
    'Antilope',
  ]),
  ...toSeeds('Profesiones', [
    'Antropologo',
    'Paleontologo',
    'Geologo',
    'Filosofo',
    'Criminologo',
    'Cartografo',
    'Epidemiologo',
    'Neurologo',
    'Oncologo',
    'Oceanografo',
    'Arqueologo',
    'Bioquimico',
    'Linguista',
    'Actuario',
    'Astrofisico',
    'Etnografo',
    'Restaurador',
  ]),
  ...toSeeds('Lugares', [
    'Archipielago',
    'Cenote',
    'Meandro',
    'Catacumbas',
    'Istmo',
    'Fiordo',
    'Delta',
    'Meseta',
    'Caldera',
    'Necropolis',
    'Cripta',
    'Cantera',
    'Peninsula',
    'Estuario',
    'Acueducto',
    'Ciudadela',
    'Barranco',
  ]),
  ...toSeeds('Deportes', [
    'Decatlon',
    'Espeleologia',
    'Parapente',
    'Biatlon',
    'Skeleton',
    'Orientacion',
    'Kitesurf',
    'Canotaje',
    'Softbol',
    'Squash',
    'Polo',
    'Ultramaraton',
    'Apnea',
    'EscaladaHielo',
    'PatinVelocidad',
    'Trampolin',
    'Ciclocross',
  ]),
  ...toSeeds('Tecnologia', [
    'Criptografia',
    'Criptomoneda',
    'Semiconductor',
    'Nanotubo',
    'Fotolitografia',
    'Transistor',
    'Kernel',
    'Compilador',
    'Contenedor',
    'Hipervisor',
    'Ciberseguridad',
    'Telemetria',
    'Lidar',
    'Biochip',
    'Neuroprotesis',
    'Superconductor',
  ]),
  ...toSeeds('Cultura', [
    'Renacimiento',
    'Barroco',
    'Surrealismo',
    'Arqueologia',
    'Hermeneutica',
    'Iconografia',
    'Retorica',
    'Epica',
    'Minimalismo',
    'Existencialismo',
    'Neoclasicismo',
    'Vanguardia',
    'Filologia',
    'Semiotica',
    'Antologia',
    'Monografia',
  ]),
  ...toSeeds('Naturaleza', [
    'Ecosistema',
    'Fotosintesis',
    'Atmosfera',
    'Biodiversidad',
    'Pangea',
    'Nebulosa',
    'Estalactita',
    'Mimetismo',
    'Tectonica',
    'Erosion',
    'Polinizacion',
    'Criosfera',
    'Hidrosfera',
    'Permafrost',
    'Bioma',
    'Estratosfera',
  ]),
];

const EXTREME_SEEDS: Seed[] = [
  ...toSeeds('Comida', [
    'GastronomiaMolecular',
    'Esferificacion',
    'FermentacionLactica',
    'Liofilizacion',
    'ReaccionMaillard',
    'Oleogel',
    'Crioconcentracion',
    'Nitrogenacion',
    'Umami',
    'Koji',
    'Gastrique',
    'Sifonado',
    'Dextrina',
    'Gelificacion',
    'Confitado',
    'EmulsionInversa',
    'Clarificacion',
  ]),
  ...toSeeds('Objetos', [
    'Interferometro',
    'Espectrometro',
    'Acelerometro',
    'Criostato',
    'Cromatografo',
    'Magnetometro',
    'Colisionador',
    'Micromanipulador',
    'Polariscopio',
    'Difractometro',
    'Refractometro',
    'Fotomultiplicador',
    'Centrifugadora',
    'Microtomo',
    'Nanolitografo',
    'Electroencefalografo',
    'Hidrofono',
  ]),
  ...toSeeds('Animales', [
    'Tardigrado',
    'Celacanto',
    'Axolote',
    'Ctenoforo',
    'Nudibranquio',
    'AyeAye',
    'Nautilo',
    'Equidna',
    'Xenopus',
    'Anfioxo',
    'Ratel',
    'MantisOrquidea',
    'CalamarColosal',
    'DragonMarino',
    'PezLinterna',
    'CaracolCono',
    'SalamandraGigante',
  ]),
  ...toSeeds('Profesiones', [
    'Epistemologo',
    'Criptoanalista',
    'Bioinformatico',
    'Neurocirujano',
    'Vulcanologo',
    'Glaciologo',
    'Paleografo',
    'Lexicografo',
    'Numismatico',
    'Sinologo',
    'Egiptologo',
    'Sismologo',
    'Micologo',
    'Etologo',
    'Nanotecnologo',
    'Astrobiologo',
    'IngenieroCuantico',
  ]),
  ...toSeeds('Lugares', [
    'Exoplaneta',
    'Singularidad',
    'PuntoLagrange',
    'Termoclina',
    'Hidrolimnion',
    'Astenosfera',
    'Magnetosfera',
    'Ionosfera',
    'FosaAbisal',
    'Atolon',
    'Karst',
    'CalderaSupervolcanica',
    'CraterImpacto',
    'DorsalOceanica',
    'PlataformaContinental',
    'CuencaEndorreica',
    'ZonaBatipelagica',
  ]),
  ...toSeeds('Deportes', [
    'Heptatlon',
    'Skyrunning',
    'Wingsuit',
    'Slackline',
    'Bobsleigh',
    'Luge',
    'Kabaddi',
    'Hurling',
    'SepakTakraw',
    'Bossaball',
    'Canicross',
    'Bikejoring',
    'PentatlonModerno',
    'Freediving',
    'UltraTrail',
    'EsquiAlpinismo',
    'CiclocrossExtremo',
  ]),
  ...toSeeds('Tecnologia', [
    'Nanotecnologia',
    'ComputacionCuantica',
    'Sincrotron',
    'Metamaterial',
    'Qubit',
    'Spintronica',
    'Fotonica',
    'Neuromorfica',
    'Optogenetica',
    'Criogenia',
    'Bioimpresion',
    'Hiperautomatizacion',
    'Ciberresiliencia',
    'TelemetriaOrbital',
    'ComputacionAnalogica',
    'IngenieriaGenomica',
  ]),
  ...toSeeds('Cultura', [
    'Epistemologia',
    'Fenomenologia',
    'Antropocentrismo',
    'Deconstruccion',
    'Postestructuralismo',
    'Metafisica',
    'Ontologia',
    'Gnoseologia',
    'FilologiaComparada',
    'PaleografiaAvanzada',
    'SemioticaCultural',
    'Anacronismo',
    'Polisemia',
    'Intertextualidad',
    'Pragmatica',
    'Exegesis',
  ]),
  ...toSeeds('Naturaleza', [
    'Entropia',
    'Termodinamica',
    'FisicaParticulas',
    'Supernova',
    'MecanicaFluidos',
    'Genoma',
    'MateriaOscura',
    'Quasar',
    'RadiacionCosmica',
    'Anisotropia',
    'Fotosfera',
    'Cromosfera',
    'Nucleosintesis',
    'Criovolcan',
    'BiosferaProfunda',
    'PlasmaInterestelar',
  ]),
];

assertCount('EASY', EASY_SEEDS.length);
assertCount('MEDIUM', MEDIUM_SEEDS.length);
assertCount('HARD', HARD_SEEDS.length);
assertCount('EXTREME', EXTREME_SEEDS.length);

export const INITIAL_WORDS: Word[] = [
  ...buildWords('f', Difficulty.EASY, EASY_SEEDS),
  ...buildWords('m', Difficulty.MEDIUM, MEDIUM_SEEDS),
  ...buildWords('h', Difficulty.HARD, HARD_SEEDS),
  ...buildWords('e', Difficulty.EXTREME, EXTREME_SEEDS),
];
